[package]
name = "fuel_frog_panic"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "main" }

[addresses]
fuel_frog_panic = "0x0"

[environments]
devnet = "e9eed8f1"
testnet = "3d6c67b7"
